### PR TITLE
Freeze fix: Disable building file list in root

### PR DESCRIPTION
**Pull request by Yrwein**
Hi, this pull should fix freeze from issue #37.
It can be reproduced by opening file outside opened folders and top_folder_hints and invoking context menu (or Sublime's command panel).

### CODE REVIEW

**Comment by cezarykluczynski** [comment]
Is this fixed in Package Control? I'm still getting massive lags with this plugin when i try to use context menu.

**Comment by stuartherbert** [comment]
The lag is caused by the plugin trying to find where the phpunit.xml file is.

I've pushed a couple of changes that should help with this in most cases. Unfortunately, if you choose to put your phpunit.xml file in an unusual place and your project is very large, then this forces the plugin to work very hard to find your file :(

Please let me know if these changes resolve your problems.

**Comment by cezarykluczynski** [comment]
It got better, down to around 4 seconds. Sadly, for me, it's still too long to wait every time.

**Comment by stuartherbert** [comment]
Thanks for the feedback. 4 seconds?!? That's horrible. I'm seeing less than 0.2 of a second, on a very large PHP project.

Can you tell me more about your project, and the machine you're running it on?

- Is the source code on a local filesystem, or on a remote filesystem?
- Is the local filesystem on an SSD, or on a spinning disk, or ...?
- Which folder is your phpunit.xml[.dist] stored in?
- How big is your project as a whole?
- Are there any folders in your project that you could add to the plugin's exclusions list?

I wonder if the best fix is to add support for a '.sublime-phpunit.json' config file, where you can explicitly tell the plugin where your phpunit.xml file is?

**Comment by cezarykluczynski** [comment]
It's pretty bad, but the PC is quite old too.

* Local filesystem.
* 4 GB RAM, Intel Core 2 Duo, magnetic storage.
* phpunit.xml.dist is in the root directory.
* https://github.com/cezarykluczynski/ComicCMS2 The project is here. It's some 150 files without dependencies.

I've added some more folders to folder_exclusions and it's down to reasonable ~0.7 s.

In the process, it turned out that adding node_modules directory to exclusion list accounted for the biggest decrease. Maybe this can be added to the default list? It's a read-only folder anyway, and phpunit.xml wouldn't be there in any sane setup.

**Comment by stuartherbert** [comment]
That's a good idea. I've just pushed a change which adds 'node_modules' to the list of exclusions.

**Pull request merged**
